/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void ejercicio_01(void) //Ejercicio 01
{
    uint8_t my_variable = 42; //Definición de variable de 8 bits

}

void ejercicio_02(void) //Ejercicio 02
{
    uint8_t dec = 65;
    uint8_t hex = 0x41; 
    uint8_t bin = 0b01000001;

}

void ejercicio_03 (void) //Ejercicio 03
{ 
    uint8_t a = 255;
    uint16_t b = 255;
    uint32_t c = 255;
    uint8_t d = 256; // El resultado será : 0, No se puede almacenar en un uint8_t, ya que excede su rango máximo de 0 a 255
    uint8_t e = 257; //El resultado será : 1, No se puede almacenar en un uint8_t, ya que excede su rango máximo de 0 a 255
}

void ejercicio_04 (void) //Ejercicio 04
{
    uint8_t a = 200;
    uint8_t b = 200;
    uint8_t c = -1; // como tengo uint (unsigned) el resultado será 255, ya que el valor -1 se interpreta como 11111111 uint8_t (255) debido a la representación en complemento a dos.

}

void ejercicio_05 (void) //Ejercicio 05
{
    int8_t x = 127; //0b01111111 predicción:-128
    x = x + 1; //128

    uint8_t y = 255;
    y = y + 1; // predicción: 0
}

void ejercicio_06 (void) //Ejercicio 06
{
    uint8_t result;

    result = 0x0F + 0x01;
    result = 0xFF + 0x01;
    result = 0xA0 + 0x5F;
    result = 0xA0 + 0x60;
}

void ejercicio_07 (void) //Ejercicio 07
{
    uint8_t x = 0;

    x = 0x01; // 00000001
    x = 0x02; // 00000010
    x = 0x04; // 00000100
    x = 0x08; // 00001000
    x = 0x10; // 00010000
    x = 0x20; // 00100000
    x = 0x40; // 01000000
    x = 0x80; // 10000000
}

void ejercicio_08 (void) //Ejercicio 08

{
    uint8_t a = 5;
    uint8_t b = 0;
    uint8_t c = 255;

    uint8_t r1 = !a; // a = 5, entonces es verdadero, por lo que !a será falso (0)
    uint8_t r2 = !b; // b = 0, entonces es falso, por lo que !b será verdadero (1)
    uint8_t r3 = !c; // c = 255, entonces es verdadero, por lo que !c será falso (0)
    uint8_t r4 = ~c; // c = 255, entonces es 11111111, por lo que ~c será 00000000 (0)

    uint8_t r5 = ~a; // a = 5, entonces es 00000101, por lo que ~a será 11111010 (250)
}


int main(void)
{
    // Llamada a la función ejercicio_01
    ejercicio_08();

    // Bucle infinito
    while (1)
    {}
}
