/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void ejercicio_01(void) //Ejercicio 01
{
    uint8_t my_variable = 42; //Definición de variable de 8 bits

}

void ejercicio_02(void) //Ejercicio 02
{
    uint8_t dec = 65;
    uint8_t hex = 0x41; 
    uint8_t bin = 0b01000001;

}

void ejercicio_03 (void) //Ejercicio 03
{ 
    uint8_t a = 255;
    uint16_t b = 255;
    uint32_t c = 255;
    uint8_t d = 256; //No se puede almacenar en un uint8_t, ya que excede su rango máximo de 0 a 255
    uint8_t e = 257; //No se puede almacenar en un uint8_t, ya que excede su rango máximo de 0 a 255
}



int main(void)
{
    // Llamada a la función ejercicio_01
    ejercicio_03();

    // Bucle infinito
    while (1)
    {}
}
