/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int ejercicio_01(void) //Ejercicio 01
{
    uint8_t my_variable = 42; //Definición de variable de 8 bits

}

int ejercicio_02(void) //Ejercicio 02
{
    uint8_t dec = 65;
    uint8_t hex = 0x41; 
    uint8_t bin = 0b01000001;

}
int main(void)
{
    // Llamada a la función ejercicio_01
    ejercicio_02();

    // Bucle infinito
    while (1)
    {}
}
